name: PR delete

on:
  pull_request:
    types: [closed, unlabeled]

env:
  AWS_REGION: eu-central-1

jobs:
  delete:
    if: |
      contains(join(github.event.pull_request.labels.*.name), 'FargateStack') &&
      (github.event.action != 'unlabeled' || !contains(github.event.pull_request.labels.*.name, 'deploy'))

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: delete AWS stack
        run: |
          cloudformationStackId=$(echo '${{ join(github.event.pull_request.labels.*.name) }}' | sed 's/.*[\^ ,]*\(FargateStack-[0-9]\{1,\}\).*/\1/')

          aws cloudformation delete-stack --stack-name $cloudformationStackId
          aws cloudformation wait stack-delete-complete --stack-name $cloudformationStackId

          taskDefinitions=$(aws resourcegroupstaggingapi get-resources --resource-type-filters ecs:task-definition --tag-filters Key=CdkStackId,Values=$cloudformationStackId --query 'ResourceTagMappingList[*].ResourceARN' --output text
          for taskDefinition in $taskDefinitions; do
            aws ecs deregister-task-definition --task-definition $taskDefinition
          done

          echo "CDK_STACK_ID=$cloudformationStackId" >> $GITHUB_ENV

      - uses: actions-ecosystem/action-remove-labels@v1
        env:
          label: ${{ env.CDK_STACK_ID }}
        with:
          labels: ${{ env.label }}
